lightblue:
  build: .
  command: /opt/jbossas7/bin/standalone.sh -b 0.0.0.0
  ports:
   - "8080:8080"
  links:
      - mongodb:mongodb
mongodb:
  image: dockerfile/mongodb
  command: mongod --rest --httpinterface --smallfiles
  ports:
   - "28017:28017"
   - "27017:27017"
applications:
  image: lightblue/applications
  command: /opt/jbossas7/bin/standalone.sh -b 0.0.0.0
  ports:
   - "8081:8080"
  links:
   - lightblue
